# Generated by Django 4.2.21 on 2025-05-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_address_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='Valor preenchido automaticamente após o evento ser criado no Google Calendar.', max_length=255, null=True, verbose_name='ID do evento do Google'),
        ),
    ]
