# Generated by Django 4.2.21 on 2025-05-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
    ]
