# Generated by Django 4.2.21 on 2025-06-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0004_lodge_number_alter_lodge_city'),
        ('events', '0005_event_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lodge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lodge.lodge', verbose_name='Loja'),
        ),
    ]
