# Generated by Django 4.2.21 on 2025-05-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Escreva a URL do sistema', max_length=255, verbose_name='URL')),
                ('email_host', models.CharField(help_text='Escreva o host do email', max_length=255, verbose_name='Host do email')),
                ('email_port', models.IntegerField(help_text='Escreva a porta do email', verbose_name='Porta do email')),
                ('email_use_ssl', models.BooleanField(default=True, help_text='Escreva se o email usa SSL', verbose_name='Usar SSL')),
                ('email_use_tls', models.BooleanField(default=False, help_text='Escreva se o email usa TLS', verbose_name='Usar TLS')),
                ('email_host_user', models.EmailField(help_text='Escreva o usuário do email', max_length=255, verbose_name='Usuário do email')),
                ('email_host_password', models.CharField(help_text='Escreva a senha do email', max_length=255, verbose_name='Senha do email')),
                ('email_timeout', models.IntegerField(default=30, help_text='Escreva o tempo de timeout do email', verbose_name='Tempo de timeout do email')),
                ('default_from_email', models.EmailField(help_text='Escreva o email padrão', max_length=255, verbose_name='Email padrão')),
                ('admin_email', models.EmailField(help_text='Escreva o email do administrador', max_length=255, verbose_name='Email do administrador')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
