# Generated by Django 4.2.21 on 2025-05-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='email_backend',
            field=models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Escreva o backend do email', max_length=255, verbose_name='Backend do email'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='email_host',
            field=models.CharField(default='smtp.hostinger.com', help_text='Escreva o host do email', max_length=255, verbose_name='Host do email'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='email_port',
            field=models.IntegerField(default=465, help_text='Escreva a porta do email', verbose_name='Porta do email'),
        ),
    ]
