# Generated by Django 4.2.21 on 2025-05-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_setup_email_backend_alter_setup_email_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='email_backend',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='email_timeout',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='email_use_ssl',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='email_use_tls',
        ),
    ]
