# Generated by Django 4.2.21 on 2025-05-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_remove_setup_email_backend_remove_setup_email_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='default_from_email',
        ),
    ]
