# Generated by Django 4.2.21 on 2025-05-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_remove_setup_default_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='calendar_url',
            field=models.CharField(default='', help_text='Escreva a URL do Google Calendar', max_length=255, verbose_name='URL do Google Calendar'),
            preserve_default=False,
        ),
    ]
