# Generated by Django 4.2.21 on 2025-06-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0004_lodge_number_alter_lodge_city'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lodge',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lodges',
            field=models.ManyToManyField(blank=True, related_name='users', to='lodge.lodge', verbose_name='Lojas'),
        ),
    ]
