# Generated by Django 4.2.21 on 2025-06-01 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0004_lodge_number_alter_lodge_city'),
        ('accounts', '0002_remove_customuser_lodge_customuser_lodges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lodges',
        ),
        migrations.CreateModel(
            name='UserLodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge.lodge', verbose_name='Loja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário Loja',
                'verbose_name_plural': 'Usuários Lojas',
            },
        ),
    ]
