# Generated by Django 4.2.21 on 2025-06-01 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_lodges_userlodge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlodge',
            options={'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
    ]
