# Generated by Django 4.2.21 on 2025-06-03 12:32

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userlodge_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brother',
            fields=[
            ],
            options={
                'verbose_name': 'Irmão',
                'verbose_name_plural': 'Irmãos',
                'ordering': ['first_name', 'last_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
