# Generated by Django 4.2.21 on 2025-05-16 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_event_options_event_created_at_and_more'),
        ('calendarrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceleventrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='canceleventrequest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='canceleventrequest',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='canceleventrequest',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Revisado'),
        ),
        migrations.AlterField(
            model_name='canceleventrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
