# Generated by Django 4.2.21 on 2025-05-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarrequest', '0002_alter_canceleventrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerequest',
            name='city',
            field=models.CharField(choices=[('RIO_DE_JANEIRO_RJ', 'Rio de Janeiro RJ'), ('SAO_PAULO_SP', 'São Paulo SP'), ('BELO_HORIZONTE_MG', 'Belo Horizonte MG'), ('SALVADOR_BA', 'Salvador BA'), ('FORTALEZA_CE', 'Fortaleza CE'), ('BRASILIA_DF', 'Brasília DF'), ('CURITIBA_PR', 'Curitiba PR'), ('MANAUS_AM', 'Manaus AM'), ('RECIFE_PE', 'Recife PE'), ('PORTO_ALEGRE_RS', 'Porto Alegre RS'), ('BELEM_PA', 'Belém PA'), ('GOIANIA_GO', 'Goiânia GO'), ('GUARULHOS_SP', 'Guarulhos SP'), ('CAMPINAS_SP', 'Campinas SP'), ('SAO_LUIS_MA', 'São Luís MA'), ('SAO_GONCALO_RJ', 'São Gonçalo RJ'), ('MACEIO_AL', 'Maceió AL'), ('DUQUE_DE_CAXIAS_RJ', 'Duque de Caxias RJ'), ('CAMPO_GRANDE_MS', 'Campo Grande MS'), ('NATAL_RN', 'Natal RN'), ('TERESINA_PI', 'Teresina PI'), ('SAO_BERNARDO_DO_CAMPO_SP', 'São Bernardo do Campo SP'), ('NOVA_IGUACU_RJ', 'Nova Iguaçu RJ'), ('JOAO_PESSOA_PB', 'João Pessoa PB'), ('SANTO_ANDRE_SP', 'Santo André SP'), ('OSASCO_SP', 'Osasco SP'), ('JABOATAO_DOS_GUARARAPES_PE', 'Jaboatão dos Guararapes PE'), ('SAO_JOSE_DOS_CAMPOS_SP', 'São José dos Campos SP'), ('RIBEIRAO_PRETO_SP', 'Ribeirão Preto SP'), ('UBERLANDIA_MG', 'Uberlândia MG'), ('SOROCABA_SP', 'Sorocaba SP'), ('CONTAGEM_MG', 'Contagem MG'), ('ARACAJU_SE', 'Aracaju SE'), ('FEIRA_DE_SANTANA_BA', 'Feira de Santana BA'), ('CUIABA_MT', 'Cuiabá MT'), ('JOINVILLE_SC', 'Joinville SC'), ('JUIZ_DE_FORA_MG', 'Juiz de Fora MG'), ('LONDRINA_PR', 'Londrina PR'), ('APARECIDA_DE_GOIANIA_GO', 'Aparecida de Goiânia GO'), ('NITEROI_RJ', 'Niterói RJ'), ('PORTO_VELHO_RO', 'Porto Velho RO'), ('SERRA_ES', 'Serra ES'), ('CAXIAS_DO_SUL_RS', 'Caxias do Sul RS'), ('MACAPA_AP', 'Macapá AP'), ('FLORIANOPOLIS_SC', 'Florianópolis SC'), ('VILA_VELHA_ES', 'Vila Velha ES'), ('MAUA_SP', 'Mauá SP'), ('SAO_JOAO_DE_MERITI_RJ', 'São João de Meriti RJ'), ('VITORIA_ES', 'Vitória ES'), ('BOA_VISTA_RR', 'Boa Vista RR'), ('PALMAS_TO', 'Palmas TO')], default='RIO_DE_JANEIRO_RJ', help_text='Selecione a cidade onde a loja está localizada', max_length=255, verbose_name='Qual é a cidade de sua loja?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerequest',
            name='power',
            field=models.CharField(default='0', help_text='Selecione a potência da sua loja', max_length=255, verbose_name='Qual é a potência da sua loja?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='approved',
            field=models.BooleanField(default=False, help_text='Marque como aprovado se a loja foi aprovada e cadastrada', verbose_name='Aprovado'),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='name',
            field=models.CharField(help_text='Escreva o nome completo da sua loja com o número. Ex: LOJA FULANO DE TAL Nº 0000', max_length=255, verbose_name='Qual é a sua loja?'),
        ),
    ]
