# Generated by Django 4.2.21 on 2025-05-16 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodge', '0002_alter_lodge_city_alter_lodge_name_alter_lodge_power'),
        ('calendarrequest', '0003_storerequest_city_storerequest_power_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(help_text='Escreva o nome do evento (feijoada, churrasco...) ou da sessão (magna grau 1, ordinária grau 2...)', max_length=200, verbose_name='Nome do evento ou sessão')),
                ('description', models.TextField(blank=True, help_text='Descreva abaixo informações importantes sobre o evento ou a ordem do dia de sua sessão.', verbose_name='Descrição')),
                ('start_time', models.DateTimeField(verbose_name='Data e hora de início')),
                ('end_time', models.DateTimeField(verbose_name='Data e hora de término')),
                ('address', models.CharField(help_text='Exemplo: Rua Y, Número, Bairro e Cidade', max_length=500, verbose_name='Qual é o endereço do evento ou sessão?')),
                ('approved', models.BooleanField(default=False, help_text='Marque como aprovado se o evento/sessão foi aprovada e cadastrada', verbose_name='Evento aprovado?')),
                ('lodge', models.ForeignKey(help_text='Qual é a sua loja?', on_delete=django.db.models.deletion.CASCADE, to='lodge.lodge', verbose_name='Loja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Solicitação de Evento/Sessão',
                'verbose_name_plural': 'Solicitações de Evento/Sessão',
            },
        ),
    ]
