# Generated by Django 4.2.21 on 2025-05-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarrequest', '0004_eventrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRequest',
        ),
    ]
