# Generated by Django 4.2.21 on 2025-05-19 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendarrequest', '0007_remove_storerequest_power_storerequest_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Escreva o nome completo do usuário', max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Escreva o email do usuário', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='Escreva o telefone do usuário', max_length=15, verbose_name='Telefone')),
                ('message', models.TextField(help_text='Escreva a mensagem do usuário', verbose_name='Mensagem')),
                ('lodge_number', models.CharField(help_text='Escreva o número da loja', max_length=20, verbose_name='Número da loja')),
                ('approved', models.BooleanField(default=False, help_text='Marque como aprovado se o usuário foi aprovado e cadastrado', verbose_name='Aprovado')),
            ],
            options={
                'verbose_name': 'Solicitação de Usuário',
                'verbose_name_plural': 'Solicitações de Usuário',
            },
        ),
    ]
