# Generated by Django 4.2.21 on 2025-05-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarrequest', '0008_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='surname',
            field=models.CharField(default='', help_text='Escreva o sobrenome do usuário', max_length=255, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='name',
            field=models.CharField(help_text='Escreva o nome do usuário', max_length=255, verbose_name='Nome'),
        ),
    ]
