# Generated by Django 4.2.21 on 2025-05-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarrequest', '0009_userrequest_surname_alter_userrequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='lodge_name',
            field=models.CharField(default='', help_text='Escreva o nome da loja', max_length=255, verbose_name='Nome da loja'),
            preserve_default=False,
        ),
    ]
