# Generated by Django 4.2.21 on 2025-05-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarrequest', '0010_userrequest_lodge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Escreva a mensagem do usuário', null=True, verbose_name='Mensagem'),
        ),
    ]
