# Generated by Django 4.2.21 on 2025-05-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarrequest', '0011_alter_userrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storerequest',
            name='city',
            field=models.CharField(choices=[('ANGRA_DOS_REIS', 'Angra dos Reis'), ('APERIBE', 'Aperibé'), ('ARARUAMA', 'Araruama'), ('AREAL', 'Areal'), ('ARMACAO_DOS_BUZIOS', 'Armação dos Búzios'), ('ARRAIAL_DO_CABO', 'Arraial do Cabo'), ('BARRA_DO_PIRAI', 'Barra do Piraí'), ('BARRA_MANSA', 'Barra Mansa'), ('BELFORD_ROXO', 'Belford Roxo'), ('BOM_JARDIM', 'Bom Jardim'), ('BOM_JESUS_DO_ITABAPOANA', 'Bom Jesus do Itabapoana'), ('CABO_FRIO', 'Cabo Frio'), ('CACHOEIRAS_DE_MACACU', 'Cachoeiras de Macacu'), ('CAMBUCI', 'Cambuci'), ('CAMPOS_DOS_GOYTACAZES', 'Campos dos Goytacazes'), ('CANTAGALO', 'Cantagalo'), ('CARAPEBUS', 'Carapebus'), ('CARDOSO_MOREIRA', 'Cardoso Moreira'), ('CARMO', 'Carmo'), ('CASIMIRO_DE_ABREU', 'Casimiro de Abreu'), ('COMENDADOR_LEVY_GASPARIAN', 'Comendador Levy Gasparian'), ('CONCEICAO_DE_MACABU', 'Conceição de Macabu'), ('CORDEIRO', 'Cordeiro'), ('DUAS_BARRAS', 'Duas Barras'), ('DUQUE_DE_CAXIAS', 'Duque de Caxias'), ('ENGENHEIRO_PAULO_DE_FRONTIN', 'Engenheiro Paulo de Frontin'), ('GUAPIMIRIM', 'Guapimirim'), ('IGUABA_GRANDE', 'Iguaba Grande'), ('ITABORAI', 'Itaboraí'), ('ITAGUAI', 'Itaguaí'), ('ITALVA', 'Italva'), ('ITAOCARA', 'Itaocara'), ('ITAPERUNA', 'Itaperuna'), ('ITATIAIA', 'Itatiaia'), ('JAPERI', 'Japeri'), ('LAJE_DO_MURIAE', 'Laje do Muriaé'), ('MACAE', 'Macaé'), ('MACUCO', 'Macuco'), ('MAGE', 'Magé'), ('MANGARATIBA', 'Mangaratiba'), ('MARICA', 'Maricá'), ('MENDES', 'Mendes'), ('MESQUITA', 'Mesquita'), ('MIGUEL_PEREIRA', 'Miguel Pereira'), ('MIRACEMA', 'Miracema'), ('NATIVIDADE', 'Natividade'), ('NILOPOLIS', 'Nilópolis'), ('NITEROI', 'Niterói'), ('NOVA_FRIBURGO', 'Nova Friburgo'), ('NOVA_IGUACU', 'Nova Iguaçu'), ('PARACAMBI', 'Paracambi'), ('PARAIBA_DO_SUL', 'Paraíba do Sul'), ('PARATY', 'Paraty'), ('PATY_DO_ALFERES', 'Paty do Alferes'), ('PETROPOLIS', 'Petrópolis'), ('PINHEIRAL', 'Pinheiral'), ('PIRAI', 'Piraí'), ('PORCIUNCULA', 'Porciúncula'), ('PORTO_REAL', 'Porto Real'), ('QUATIS', 'Quatis'), ('QUEIMADOS', 'Queimados'), ('QUISSAMA', 'Quissamã'), ('RESENDE', 'Resende'), ('RIO_BONITO', 'Rio Bonito'), ('RIO_CLARO', 'Rio Claro'), ('RIO_DAS_FLORES', 'Rio das Flores'), ('RIO_DAS_OSTRAS', 'Rio das Ostras'), ('RIO_DE_JANEIRO', 'Rio de Janeiro'), ('SANTA_MARIA_MADALENA', 'Santa Maria Madalena'), ('SANTO_ANTONIO_DE_PADUA', 'Santo Antônio de Pádua'), ('SAO_FIDELIS', 'São Fidélis'), ('SAO_FRANCISCO_DE_ITABAPOANA', 'São Francisco de Itabapoana'), ('SAO_GONCALO', 'São Gonçalo'), ('SAO_JOAO_DA_BARRA', 'São João da Barra'), ('SAO_JOAO_DE_MERITI', 'São João de Meriti'), ('SAO_JOSE_DE_UBA', 'São José de Ubá'), ('SAO_JOSE_DO_VALE_DO_RIO_PRETO', 'São José do Vale do Rio Preto'), ('SAO_PEDRO_DA_ALDEIA', 'São Pedro da Aldeia'), ('SAO_SEBASTIAO_DO_ALTO', 'São Sebastião do Alto'), ('SAPUCAIA', 'Sapucaia'), ('SAQUAREMA', 'Saquarema'), ('SEROPEDICA', 'Seropédica'), ('SILVA_JARDIM', 'Silva Jardim'), ('SUMIDOURO', 'Sumidouro'), ('TANGUA', 'Tanguá'), ('TERESOPOLIS', 'Teresópolis'), ('TRAJANO_DE_MORAES', 'Trajano de Moraes'), ('TRES_RIOS', 'Três Rios'), ('VALENCA', 'Valença'), ('VARRE_SAI', 'Varre-Sai'), ('VASSOURAS', 'Vassouras'), ('VOLTA_REDONDA', 'Volta Redonda')], help_text='Selecione a cidade onde a loja está localizada', max_length=255, verbose_name='Cidade'),
        ),
    ]
