# Generated by Django 4.2.23 on 2025-08-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_profession'),
        ('calendarrequest', '0012_alter_storerequest_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='profession',
            field=models.ForeignKey(blank=True, help_text='Selecione sua profissão', null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.profession', verbose_name='Profissão'),
        ),
    ]
