# Generated by Django 4.2.21 on 2025-05-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0002_alter_lodge_city_alter_lodge_name_alter_lodge_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodge',
            name='power',
        ),
    ]
